### ISSUE TITLE
Update default Feathers Secret to be 2048 bit

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-generator#50]
@marshallswain pointed out to me in Slack that our current auto-generated keys are too small. They are only about 300-400 bits. HS256 algorithm for JWTs should have a secret of at least 1024 bits if not 2056 or more so that they can't be easily brute forced.

We should use `crypto.randomBytes(2048).toString('hex')` for secret creation.

**Comment by daffl** [comment]
The current generator uses a 64 character string (see https://github.com/feathersjs/generator-feathers/blob/master/generators/secret/index.js#L15).

JavaScript uses UTF-16 for a character encoding so we should have 64*16 = 1024 bits. We could definitely double it to 128 characters though.

**Comment by marshallswain** [comment]
Oh good.  I assumed it was using UTF-8.  I would prefer to use the crypto library to generate the secret because it's not limited to randomstring's `alphanumeric - [0-9 a-z A-Z]` setting.  The downside is that the secrets will be much longer in `hex` format.  A random string of 128 characters is technically a 2048-bit secret, but I don't think we want to limit our character set.  Looking at [this example of string output from crypto.randomBytes](https://runkit.com/58c85dd7f647230015787e2c/58e255092830330014a7c385), there seem to be more characters used in the `utf8` output than what's represented by my default font.  I'm not a pro at this, so there could be another explanation.

**Comment by marshallswain** [comment]
I made this change to the other generator, here: https://github.com/feathersjs/generator-feathers/pull/195

**Comment by daffl** [comment]
Done and released. Closing.
